Feature show widget/layer in similar datasets section
resource-watch/resource-watch-app pull request #35
Opened 2017-03-15 13:50 UTC by pablopareja

The following extra changes are included:

- Placeholder component
- Load datasets with no default widget/layer in both Explore and Explore Detail pages
- Hide Similar datasets section in Explore Detail when none was found

2017-03-15 14:25 UTC, pablopareja commented
@mbarrenechea can you have a look at this? 
I have added the sidebar with the map view

2017-03-15 14:51 UTC, mbarrenechea requested changes
Apart from this little thing, really good work

2017-03-15 14:51 UTC, mbarrenechea commented on src/components/pages/ExploreDetail.jsx
>      const buttonClass = (hasLayer) ? '-active' : '';
Let's use classnames instead of using ternary conditions

2017-03-15 15:02 UTC, pablopareja commented
I've just fixed the classnames issue for the button. Besides that the default layer is already being displayed at the Explore Detail page.
@mbarrenechea can you check it out?

2017-03-15 15:03 UTC, mbarrenechea requested changes

2017-03-15 15:03 UTC, mbarrenechea commented on src/components/pages/ExploreDetail.jsx
> +            layersActive={[dataset.detail.attributes.layer[0].attributes]}
Why are you using the layer[0]? Shouldn't be the default one?

2017-03-15 15:03 UTC, mbarrenechea commented on src/components/pages/ExploreDetail.jsx
> +            layersActive={[dataset.detail.attributes.layer[0].attributes]}
The same here

2017-03-15 15:34 UTC, pablopareja commented on src/components/pages/ExploreDetail.jsx
> +            layersActive={[dataset.detail.attributes.layer[0].attributes]}
fixed!

2017-03-15 15:34 UTC, pablopareja commented on src/components/pages/ExploreDetail.jsx
> +            layersActive={[dataset.detail.attributes.layer[0].attributes]}
fixed!

2017-03-16 15:24 UTC, mbarrenechea approved these changes

2017-03-16 15:24 UTC, merged